apiVersion: apps/v1
kind: Deployment
metadata:
  name: item
spec:
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
      - name: item
        image: shubh141/item-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item
  ports:
  - port: 8080
    targetPort: 8080
