global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'item-service'
    static_configs:
      - targets: ['item-service:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']
