tempo:
  config: |
    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1000000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo

  pvc:
    enabled: true
    storage: 1Gi
    accessMode1: ReadWriteOnce
    storageClassName: standard-rwo

  service:
    type: ClusterIP
    port1: 3200
    targetPort1: 3200
    port2: 4318
    targetPort2: 4318


prometheus:
  scrapeInterval: 5s
  containerPort: 9090
  servicePort: 9090


grafana:
  image:
    repository: grafana/grafana-oss
    tag: latest

  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: ""

  env:
    GF_TRACING_ENABLED: "true"
    GF_TRACING_TEMPO_URL: "http://tempo:3200"

  service:
    type: ClusterIP
    port: 3000

  securityContext:
    fsGroup: 472

  serviceAccount:
    create: true
