tempo:
  config: |
    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1000000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo

  pvc:
    enabled: true
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: standard-rwo

  service:
    type: ClusterIP
    ports:
      - name: tempo-ui
        port: 3200
        targetPort: 3200
      - name: otlp-http
        port: 4318
        targetPort: 4318


prometheus:
  prometheusSpec:
    scrapeInterval: "5s"
    additionalScrapeConfigs:
      - job_name: 'item-service'
        static_configs:
          - targets: ['item-service:8080']
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8081']


grafana:
  image:
    repository: grafana/grafana-oss
    tag: latest

  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: ""

  env:
    GF_TRACING_ENABLED: "true"
    GF_TRACING_TEMPO_URL: "http://tempo:3200"

  service:
    type: ClusterIP
    port: 3000

  securityContext:
    fsGroup: 472

  serviceAccount:
    create: true
