---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-order
spec:
  selector:
    app: redis-order
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
