---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-item
spec:
  selector:
    app: redis-item
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
