apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: 'item-service'
        static_configs:
          - targets: ['item-service:8080']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8081']

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: {{ .Values.prometheus.servicePort }}
      targetPort: {{ .Values.prometheus.containerPort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: {{ .Values.prometheus.containerPort }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-prometheus-config
