apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app: tempo
data:
  tempo.yaml: |
    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1000000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: storage
              mountPath: /tmp/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: storage
          persistentVolumeClaim:
            claimName: tempo-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  labels:
    app: tempo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: tempo-ui
      port: 3200
      targetPort: 3200
    - name: otlp-http
      port: 4318
      targetPort: 4318
