---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app: tempo
data:
  tempo.yaml: |-
{{ .Values.tempo.config | indent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: storage
              mountPath: /tmp/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: storage
          persistentVolumeClaim:
            claimName: tempo-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  labels:
    app: tempo
spec:
  accessModes:
{{- range .Values.tempo.pvc.accessModes }}
  - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.tempo.pvc.storage }}
  storageClassName: {{ .Values.tempo.pvc.storageClassName }}

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  type: {{ .Values.tempo.service.type }}
  ports:
{{- range .Values.tempo.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
{{- end }}
